- name: Commit time.txt to repo
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: |
    # 设置git配置
    git config user.name "github-actions[bot]"
    git config user.email "github-actions[bot]@users.noreply.github.com"
    
    # 确保在仓库根目录
    cd "${GITHUB_WORKSPACE}"
    
    # 拉取最新代码避免冲突
    git pull origin main
    
    # 更新时间文件
    if [ ! -f time.txt ]; then
      echo "首次生成时间：$(date +'%Y-%m-%d %H:%M:%S')" > time.txt
    else
      echo "$(date +'%Y-%m-%d %H:%M:%S')" > time.txt
    fi
    
    git add time.txt
    
    # 检查是否有变化
    if git diff --cached --quiet; then
      echo "无变化，无需提交"
    else
      git commit -m "⏱️ 更新时间文件: $(date +'%Y-%m-%d %H:%M:%S')"
      git push origin HEAD:main
    fi
